### ISSUE TITLE
Genes cutoff in dropdown

### ISSUE THREAD

**Issue by ssadedin** [bioinfomethods/mitoreport#3]
All the genes are cutoff in the gene filter dropdown:

![image](https://user-images.githubusercontent.com/138868/155668809-15372331-6534-464f-a9a2-6e555a409081.png)

There seems to be a lot of padding / space b/w the checkbox and the gene symbol. Can it be reduced?

**Comment by david-ma** [comment]
Issue migrated to gitlab
